/**
 * This file is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This file implements the functions for encoding and decoding the
 * 'drip_ack_msg' message type. See drip_ack_msg.h for more details.
 */

#include <message.h>
#include "drip_ack_msg.h"

uint8_t drip_ack_msg_type_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 0, 8);
}

void drip_ack_msg_type_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 0, 8, value);
}

uint8_t drip_ack_msg_updated_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 8, 8);
}

void drip_ack_msg_updated_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 8, 8, value);
}

uint16_t drip_ack_msg_id_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 16, 16);
}

void drip_ack_msg_id_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 16, 16, value);
}

