/**
 * This file is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This file defines the layout of the 'drip_ack_msg' message type.
 */

#ifndef DRIP_ACK_MSG_H
#define DRIP_ACK_MSG_H
#include <message.h>

enum {
  /** The default size of this message type in bytes. */
  DRIP_ACK_MSG_SIZE = 4,

  /** The Active Message type associated with this message. */
  DRIP_ACK_MSG_AM_TYPE = 7,

  /* Field type: type uint8_t, offset (bits) 0, size (bits) 8 */
  /** Offset (in bytes) of the field 'type' */
  DRIP_ACK_MSG_TYPE_OFFSET = 0,
  /** Offset (in bits) of the field 'type' */
  DRIP_ACK_MSG_TYPE_OFFSETBITS = 0,
  /** Size (in bytes) of the field 'type' */
  DRIP_ACK_MSG_TYPE_SIZE = 1,
  /** Size (in bits) of the field 'type' */
  DRIP_ACK_MSG_TYPE_SIZEBITS = 8,

  /* Field updated: type uint8_t, offset (bits) 8, size (bits) 8 */
  /** Offset (in bytes) of the field 'updated' */
  DRIP_ACK_MSG_UPDATED_OFFSET = 1,
  /** Offset (in bits) of the field 'updated' */
  DRIP_ACK_MSG_UPDATED_OFFSETBITS = 8,
  /** Size (in bytes) of the field 'updated' */
  DRIP_ACK_MSG_UPDATED_SIZE = 1,
  /** Size (in bits) of the field 'updated' */
  DRIP_ACK_MSG_UPDATED_SIZEBITS = 8,

  /* Field id: type uint16_t, offset (bits) 16, size (bits) 16 */
  /** Offset (in bytes) of the field 'id' */
  DRIP_ACK_MSG_ID_OFFSET = 2,
  /** Offset (in bits) of the field 'id' */
  DRIP_ACK_MSG_ID_OFFSETBITS = 16,
  /** Size (in bytes) of the field 'id' */
  DRIP_ACK_MSG_ID_SIZE = 2,
  /** Size (in bits) of the field 'id' */
  DRIP_ACK_MSG_ID_SIZEBITS = 16,
};

/**
 * Return the value of the field 'type'
 */
uint8_t drip_ack_msg_type_get(tmsg_t *msg);

/**
 * Set the value of the field 'type'
 */
void drip_ack_msg_type_set(tmsg_t *msg, uint8_t value);

/**
 * Return the value of the field 'updated'
 */
uint8_t drip_ack_msg_updated_get(tmsg_t *msg);

/**
 * Set the value of the field 'updated'
 */
void drip_ack_msg_updated_set(tmsg_t *msg, uint8_t value);

/**
 * Return the value of the field 'id'
 */
uint16_t drip_ack_msg_id_get(tmsg_t *msg);

/**
 * Set the value of the field 'id'
 */
void drip_ack_msg_id_set(tmsg_t *msg, uint16_t value);

#endif
